# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.x'

- script: |
    python -m venv venv
    source venv/bin/activate
    pip install -r requirements.txt
  displayName: 'Instalar dependências'

- script: |
    echo "Testes placeholder - insira seus testes aqui"
  displayName: 'Executar Testes'

- script: |
    echo "Deploy automático seria configurado aqui"
  displayName: 'Deploy'

- task: CopyFilesOverSSH@0
  inputs:
    sshEndpoint: 'github.com_caduunisal'
    sourceFolder: '$(Build.SourcesDirectory)'
    contents: '**'
    targetFolder: '/home/usuario/app'

- script: |
    ssh usuario@ip-da-vm 'cd /home/usuario/app && nohup python3 app.py &'
  displayName: 'Rodar app Flask na VM'

